#########################
## Bundler: Ruby Version Management
## http://bundler.io/
##
## Gemfile Overview:
##  http://bundler.io/v1.3/gemfile.html
##
## Bundler Commands:
##   install
##     http://bundler.io/v1.3/bundle_install.html
##   update
##     http://bundler.io/v1.3/bundle_update.html
#########################

# Fetch our gems from RubyGems
source 'https://rubygems.org'

# Use the prescribed versions of the following gems
gem 'breakpoint', '~>2.5.0'
gem 'compass', '1.0.1'
gem 'sass', '~>3.4.14'
gem 'sass-globbing', '~>1.1.1'
gem 'susy'
gem 'toolkit', '~>2.6.0'
